# Generated by Django 4.2.6 on 2023-12-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker_game', '0003_attempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
